# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'marde_tanha.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Aavar(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(492, 665)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd452,stop:0.5 #f05053, stop:1 #ffd452 );\n"
"\n"
"border-radius:15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_bachat = QtWidgets.QPushButton(self.frame)
        self.pushButton_bachat.setEnabled(True)
        self.pushButton_bachat.setGeometry(QtCore.QRect(110, 100, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_bachat.setFont(font)
        self.pushButton_bachat.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_bachat.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_bachat.setObjectName("pushButton_bachat")
        self.pushButton_nemitarsam = QtWidgets.QPushButton(self.frame)
        self.pushButton_nemitarsam.setEnabled(True)
        self.pushButton_nemitarsam.setGeometry(QtCore.QRect(110, 160, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_nemitarsam.setFont(font)
        self.pushButton_nemitarsam.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_nemitarsam.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_nemitarsam.setObjectName("pushButton_nemitarsam")
        self.pushButton_shorou = QtWidgets.QPushButton(self.frame)
        self.pushButton_shorou.setEnabled(True)
        self.pushButton_shorou.setGeometry(QtCore.QRect(110, 220, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_shorou.setFont(font)
        self.pushButton_shorou.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_shorou.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_shorou.setObjectName("pushButton_shorou")
        self.pushButton_majnoun = QtWidgets.QPushButton(self.frame)
        self.pushButton_majnoun.setEnabled(True)
        self.pushButton_majnoun.setGeometry(QtCore.QRect(110, 280, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_majnoun.setFont(font)
        self.pushButton_majnoun.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_majnoun.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_majnoun.setObjectName("pushButton_majnoun")
        self.pushButton_atal = QtWidgets.QPushButton(self.frame)
        self.pushButton_atal.setEnabled(True)
        self.pushButton_atal.setGeometry(QtCore.QRect(110, 400, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_atal.setFont(font)
        self.pushButton_atal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_atal.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_atal.setObjectName("pushButton_atal")
        self.pushButton_doshab = QtWidgets.QPushButton(self.frame)
        self.pushButton_doshab.setEnabled(True)
        self.pushButton_doshab.setGeometry(QtCore.QRect(110, 340, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_doshab.setFont(font)
        self.pushButton_doshab.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_doshab.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_doshab.setObjectName("pushButton_doshab")
        self.pushButtoon_baman = QtWidgets.QPushButton(self.frame)
        self.pushButtoon_baman.setEnabled(True)
        self.pushButtoon_baman.setGeometry(QtCore.QRect(110, 460, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtoon_baman.setFont(font)
        self.pushButtoon_baman.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtoon_baman.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButtoon_baman.setObjectName("pushButtoon_baman")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(190, 20, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Dosis ExtraBold")
        font.setPointSize(31)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: none;\n"
"color:#ffd452;\n"
"")
        self.label.setObjectName("label")
        self.pushButton_exit = QtWidgets.QPushButton(self.frame)
        self.pushButton_exit.setGeometry(QtCore.QRect(410, 44, 18, 18))
        self.pushButton_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_exit.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_exit.setText("")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_back = QtWidgets.QPushButton(self.frame)
        self.pushButton_back.setGeometry(QtCore.QRect(410, 112, 18, 18))
        self.pushButton_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_back.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_back.setText("")
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_min = QtWidgets.QPushButton(self.frame)
        self.pushButton_min.setGeometry(QtCore.QRect(410, 78, 18, 18))
        self.pushButton_min.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_min.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_min.setText("")
        self.pushButton_min.setObjectName("pushButton_min")
        self.pushButton_avar = QtWidgets.QPushButton(self.frame)
        self.pushButton_avar.setEnabled(True)
        self.pushButton_avar.setGeometry(QtCore.QRect(113, 520, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_avar.setFont(font)
        self.pushButton_avar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_avar.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_avar.setObjectName("pushButton_avar")
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_exit.clicked.connect(MainWindow.close)
        self.pushButton_min.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_bachat.setText(_translate("MainWindow", "Be-Bachat-Begoo"))
        self.pushButton_nemitarsam.setText(_translate("MainWindow", "Nemitarsam"))
        self.pushButton_shorou.setText(_translate("MainWindow", "Shorou"))
        self.pushButton_majnoun.setText(_translate("MainWindow", "Majnoune-shahr"))
        self.pushButton_atal.setText(_translate("MainWindow", "Atal-matal"))
        self.pushButton_doshab.setText(_translate("MainWindow", "Do-shab"))
        self.pushButtoon_baman.setText(_translate("MainWindow", "Ba-man-ghadam-bezan"))
        self.label.setText(_translate("MainWindow", "Aavar"))
        self.pushButton_avar.setText(_translate("MainWindow", "Aavar"))
