# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'text.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Beshnas(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(524, 667)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 212, 82);\n"
"\n"
"border-radius:15px;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMouseTracking(False)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 489, 5018))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(0, 5000))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(-10, 10, 451, 4991))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:none;\n"
"color: #f05053;")
        self.label.setObjectName("label")
        self.pushButton_exit = QtWidgets.QPushButton(self.frame)
        self.pushButton_exit.setGeometry(QtCore.QRect(400, 30, 18, 18))
        self.pushButton_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_exit.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_exit.setText("")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_min = QtWidgets.QPushButton(self.frame)
        self.pushButton_min.setGeometry(QtCore.QRect(370, 30, 18, 18))
        self.pushButton_min.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_min.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_min.setText("")
        self.pushButton_min.setObjectName("pushButton_min")
        self.pushButton_max = QtWidgets.QPushButton(self.frame)
        self.pushButton_max.setGeometry(QtCore.QRect(340, 30, 18, 18))
        self.pushButton_max.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_max.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_max.setText("")
        self.pushButton_max.setObjectName("pushButton_max")
        self.verticalLayout_2.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_min.clicked.connect(MainWindow.showMinimized)
        self.pushButton_exit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "منو بشناس\n"
"\n"
"من سرشار از غم و احساس\n"
"\n"
"من تاریکم پر از اشکال\n"
"\n"
"با گوش پر از فحش و اخطار از\n"
"\n"
"دنیای آدما اخراجم\n"
"\n"
"منو به ذهنت بسپار\n"
"\n"
"من زودتر از این حرفا رفتنیم\n"
"\n"
"پس نمیتونم دنیا رو سخت نگیرم\n"
"\n"
"شکل یه شبکه ی بَرفکیم\n"
"\n"
"شکل یه کاغذ خط خطیم\n"
"\n"
"یه تصویر عجیب ضرب دریم\n"
"\n"
"که پاییزمو بهار پس زمینم\n"
"\n"
"حقمو مَحاله پس نگیرم\n"
"\n"
"محاله هر شب نشینم\n"
"\n"
"پای کلمه ها خودکار و دست نگیرم\n"
"\n"
"من خیلی خیلی زود رفتنیم پس همینم\n"
"\n"
"قشنگ شده واسم بعضی کارا\n"
"\n"
"شِمردن تعداد ته سیگارا\n"
"\n"
"نوشتن از همه دردای دلم روی کاغذ حتی رو درو دیوارا\n"
"\n"
"الکی نمی خوام روزام و شب کنم\n"
"\n"
"الکی واسه پول شهرت تب کنم\n"
"\n"
"وقتی مینویسم یه آدم دیگم\n"
"\n"
"می خوام هرچی که میدونم و رپ کنمش\n"
"\n"
"خسته أ دنیا ایستِ بازرساش\n"
"\n"
"تلاش واسه نمره بیست داوراش\n"
"\n"
"این صدا واسه بی صدا تراش\n"
"\n"
"واسه فریاد بستمش شیش کلاس\n"
"\n"
"منو خوب به حافظت بسپار\n"
"\n"
"منو حسم کن منو بشناس\n"
"\n"
"اگه دوست داری بهتر حفظم کنی\n"
"\n"
"ثانیه های شبو بشمار\n"
"\n"
"منو بشناس بدون استخاره\n"
"\n"
"حرفای تلخه من قصه سازه\n"
"\n"
"سرشار از غم اعتراضه\n"
"\n"
"منو حفظم کن مثِ شعر حافظ\n"
"\n"
"منو بشناس بینمون اختلافه\n"
"\n"
"دنیای من پر از اقتداره\n"
"\n"
"دنیای من همون اتفاقه\n"
"\n"
"که تووش پره کینه و انتقامه\n"
"\n"
"منو بشناس بدون استخاره\n"
"\n"
"حرفای تلخه من قصه سازه\n"
"\n"
"سرشار از غم اعتراضه\n"
"\n"
"منو حفظم کن مثِ شعر حافظ\n"
"\n"
"منو بشناس بینمون اختلافه\n"
"\n"
"دنیای من پر از اقتداره\n"
"\n"
"دنیای من همون اتفاقه\n"
"\n"
"که تووش پره کینه و انتقامه\n"
"\n"
"واسه اون که توو زندگی پیره\n"
"\n"
"واسه اون شبایِ تار و تیره\n"
"\n"
"واسه اون که توو زندان گیره\n"
"\n"
"جیبش خالیه و مسیرو میره بی حس\n"
"\n"
"واسه اون زن بیوه\n"
"\n"
"وقتی چشما میشن بهش خیره\n"
"\n"
"واسه اون که می گفتن شیره\n"
"\n"
"اما حالا شده نعشه ی شیره\n"
"\n"
"واسه کارگر بدون جیره\n"
"\n"
"بستن پینه رو دست ضعیفش\n"
"\n"
"واسه مادر و قلب مریضش\n"
"\n"
"واسه زندگی غرق هزینه\n"
"\n"
"از دست رفتن یه عزیزش این قصه ی درد عجیبه\n"
"\n"
"دردی که به همه ی سلولای بدن امثال شماها غریبه\n"
"\n"
"واسه کسی که می خواد شَرو کمش کنه\n"
"\n"
"کسی که می خواد هیپ هاپ و جمعش کنه\n"
"\n"
"اونی که با راست گفتن ماها مشکل داره\n"
"\n"
"واس خاطر اینکه چپش پره\n"
"\n"
"واسه اداره ها و همه پُستای کَشکی\n"
"\n"
"واسه بانکا و دزدای شرعی\n"
"\n"
"واسه کار بلدای کار شل کن\n"
"\n"
"واسه راه بلدای راه گم کن\n"
"\n"
"واسه گنده مَنصبای گردن کلفت\n"
"\n"
"همون آدمای مفت خور\n"
"\n"
"واسه تویی که می دونی یهو پر شدن چیه\n"
"\n"
"لای جمعیت گُم شدن چیه\n"
"\n"
"تویی که می دونی یهو خُل شدن چیه\n"
"\n"
"درگیر الکل شدن چیه\n"
"\n"
"گوش کن توو مخت بسپار\n"
"\n"
"هر کلمه ی منو بشکاف\n"
"\n"
"من هستم تا این داستانا هستن\n"
"\n"
"منو حس کن منو بشناس من غمگینم\n"
"\n"
"از دردا و غصه ها سنگینم\n"
"\n"
"بشین به حرفام فکر کن\n"
"\n"
"هر کلمه ی منو حس کن\n"
"\n"
"منو بشناس بدون استخاره\n"
"\n"
"حرفای تلخه من قصه سازه\n"
"\n"
"سرشار از غم اعتراضه\n"
"\n"
"منو حفظم کن مثِ شعر حافظ\n"
"\n"
"منو بشناس بینمون اختلافه\n"
"\n"
"دنیای من پر از اقتداره\n"
"\n"
"دنیای من همون اتفاقه\n"
"\n"
"که تووش پره کینه و انتقامه\n"
"\n"
"منو بشناس بدون استخاره\n"
"\n"
"حرفای تلخه من قصه سازه\n"
"\n"
"سرشار از غم اعتراضه\n"
"\n"
"منو حفظم کن مثِ شعر حافظ\n"
"\n"
"منو بشناس بینمون اختلافه\n"
"\n"
"دنیای من پر از اقتداره\n"
"\n"
"دنیای من همون اتفاقه\n"
"\n"
"که تووش پره کینه و انتقامه"))

