# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'marde_tanha.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Gavazn(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(586, 635)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd452,stop:0.5 #f05053, stop:1 #ffd452 );\n"
"\n"
"border-radius:15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_Harkat = QtWidgets.QPushButton(self.frame)
        self.pushButton_Harkat.setEnabled(True)
        self.pushButton_Harkat.setGeometry(QtCore.QRect(70, 100, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Harkat.setFont(font)
        self.pushButton_Harkat.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Harkat.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_Harkat.setObjectName("pushButton_Harkat")
        self.pushButton_nakhoda = QtWidgets.QPushButton(self.frame)
        self.pushButton_nakhoda.setEnabled(True)
        self.pushButton_nakhoda.setGeometry(QtCore.QRect(70, 160, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_nakhoda.setFont(font)
        self.pushButton_nakhoda.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_nakhoda.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_nakhoda.setObjectName("pushButton_nakhoda")
        self.pushButton_daar = QtWidgets.QPushButton(self.frame)
        self.pushButton_daar.setEnabled(True)
        self.pushButton_daar.setGeometry(QtCore.QRect(70, 220, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_daar.setFont(font)
        self.pushButton_daar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_daar.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_daar.setObjectName("pushButton_daar")
        self.pushButton_goriz = QtWidgets.QPushButton(self.frame)
        self.pushButton_goriz.setEnabled(True)
        self.pushButton_goriz.setGeometry(QtCore.QRect(70, 280, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_goriz.setFont(font)
        self.pushButton_goriz.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_goriz.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_goriz.setObjectName("pushButton_goriz")
        self.pushButton_ghalbhaye = QtWidgets.QPushButton(self.frame)
        self.pushButton_ghalbhaye.setEnabled(True)
        self.pushButton_ghalbhaye.setGeometry(QtCore.QRect(70, 400, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ghalbhaye.setFont(font)
        self.pushButton_ghalbhaye.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_ghalbhaye.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_ghalbhaye.setObjectName("pushButton_ghalbhaye")
        self.pushButton_bad_pichid = QtWidgets.QPushButton(self.frame)
        self.pushButton_bad_pichid.setEnabled(True)
        self.pushButton_bad_pichid.setGeometry(QtCore.QRect(70, 340, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_bad_pichid.setFont(font)
        self.pushButton_bad_pichid.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_bad_pichid.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_bad_pichid.setObjectName("pushButton_bad_pichid")
        self.pushButtoon_laghzesh = QtWidgets.QPushButton(self.frame)
        self.pushButtoon_laghzesh.setEnabled(True)
        self.pushButtoon_laghzesh.setGeometry(QtCore.QRect(70, 460, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtoon_laghzesh.setFont(font)
        self.pushButtoon_laghzesh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtoon_laghzesh.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButtoon_laghzesh.setObjectName("pushButtoon_laghzesh")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(210, 10, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Dosis ExtraBold")
        font.setPointSize(31)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: none;\n"
"color:#ffd452;\n"
"")
        self.label.setObjectName("label")
        self.pushButton_exit = QtWidgets.QPushButton(self.frame)
        self.pushButton_exit.setGeometry(QtCore.QRect(510, 44, 18, 18))
        self.pushButton_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_exit.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_exit.setText("")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_back = QtWidgets.QPushButton(self.frame)
        self.pushButton_back.setGeometry(QtCore.QRect(510, 112, 18, 18))
        self.pushButton_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_back.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_back.setText("")
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_min = QtWidgets.QPushButton(self.frame)
        self.pushButton_min.setGeometry(QtCore.QRect(510, 78, 18, 18))
        self.pushButton_min.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_min.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_min.setText("")
        self.pushButton_min.setObjectName("pushButton_min")
        self.pushButtoon_cut = QtWidgets.QPushButton(self.frame)
        self.pushButtoon_cut.setEnabled(True)
        self.pushButtoon_cut.setGeometry(QtCore.QRect(280, 460, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtoon_cut.setFont(font)
        self.pushButtoon_cut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtoon_cut.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButtoon_cut.setObjectName("pushButtoon_cut")
        self.pushButton_asayeshgah = QtWidgets.QPushButton(self.frame)
        self.pushButton_asayeshgah.setEnabled(True)
        self.pushButton_asayeshgah.setGeometry(QtCore.QRect(280, 340, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_asayeshgah.setFont(font)
        self.pushButton_asayeshgah.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_asayeshgah.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_asayeshgah.setObjectName("pushButton_asayeshgah")
        self.pushButton_dashte = QtWidgets.QPushButton(self.frame)
        self.pushButton_dashte.setEnabled(True)
        self.pushButton_dashte.setGeometry(QtCore.QRect(280, 400, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_dashte.setFont(font)
        self.pushButton_dashte.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_dashte.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_dashte.setObjectName("pushButton_dashte")
        self.pushButton_gavazn = QtWidgets.QPushButton(self.frame)
        self.pushButton_gavazn.setEnabled(True)
        self.pushButton_gavazn.setGeometry(QtCore.QRect(280, 100, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_gavazn.setFont(font)
        self.pushButton_gavazn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_gavazn.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_gavazn.setObjectName("pushButton_gavazn")
        self.pushButton_pelikan = QtWidgets.QPushButton(self.frame)
        self.pushButton_pelikan.setEnabled(True)
        self.pushButton_pelikan.setGeometry(QtCore.QRect(280, 220, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_pelikan.setFont(font)
        self.pushButton_pelikan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_pelikan.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_pelikan.setObjectName("pushButton_pelikan")
        self.pushButton_istgah = QtWidgets.QPushButton(self.frame)
        self.pushButton_istgah.setEnabled(True)
        self.pushButton_istgah.setGeometry(QtCore.QRect(280, 160, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_istgah.setFont(font)
        self.pushButton_istgah.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_istgah.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_istgah.setObjectName("pushButton_istgah")
        self.pushButton_na_mimiram = QtWidgets.QPushButton(self.frame)
        self.pushButton_na_mimiram.setEnabled(True)
        self.pushButton_na_mimiram.setGeometry(QtCore.QRect(280, 280, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_na_mimiram.setFont(font)
        self.pushButton_na_mimiram.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_na_mimiram.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_na_mimiram.setObjectName("pushButton_na_mimiram")
        self.pushButtoon_daroon = QtWidgets.QPushButton(self.frame)
        self.pushButtoon_daroon.setEnabled(True)
        self.pushButtoon_daroon.setGeometry(QtCore.QRect(70, 520, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtoon_daroon.setFont(font)
        self.pushButtoon_daroon.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtoon_daroon.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButtoon_daroon.setObjectName("pushButtoon_daroon")
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_exit.clicked.connect(MainWindow.close)
        self.pushButton_min.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Harkat.setText(_translate("MainWindow", "Harkat"))
        self.pushButton_nakhoda.setText(_translate("MainWindow", "Nakhoda-Jelal"))
        self.pushButton_daar.setText(_translate("MainWindow", "Daar"))
        self.pushButton_goriz.setText(_translate("MainWindow", "Goriz-az-markaz"))
        self.pushButton_ghalbhaye.setText(_translate("MainWindow", "Ghalbhaye-atashin"))
        self.pushButton_bad_pichid.setText(_translate("MainWindow", "Bad-pichid"))
        self.pushButtoon_laghzesh.setText(_translate("MainWindow", "Laghzesh"))
        self.label.setText(_translate("MainWindow", "Gavazn"))
        self.pushButtoon_cut.setText(_translate("MainWindow", "Cut"))
        self.pushButton_asayeshgah.setText(_translate("MainWindow", "Asayeshgah"))
        self.pushButton_dashte.setText(_translate("MainWindow", "Dashte-parvaneha"))
        self.pushButton_gavazn.setText(_translate("MainWindow", "Gavazn"))
        self.pushButton_pelikan.setText(_translate("MainWindow", "Pelikan"))
        self.pushButton_istgah.setText(_translate("MainWindow", "Istgah-shahr-yakh"))
        self.pushButton_na_mimiram.setText(_translate("MainWindow", "Na-mimiram ..."))
        self.pushButtoon_daroon.setText(_translate("MainWindow", "Daroon[skit]"))

