# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'text.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GharibeNisti(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(496, 667)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 212, 82);\n"
"\n"
"border-radius:15px;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMouseTracking(False)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 461, 5018))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(0, 5000))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(-10, 0, 371, 5001))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:none;\n"
"color: #f05053;")
        self.label.setObjectName("label")
        self.pushButton_exit = QtWidgets.QPushButton(self.frame)
        self.pushButton_exit.setGeometry(QtCore.QRect(400, 30, 18, 18))
        self.pushButton_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_exit.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_exit.setText("")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_min = QtWidgets.QPushButton(self.frame)
        self.pushButton_min.setGeometry(QtCore.QRect(370, 30, 18, 18))
        self.pushButton_min.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_min.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_min.setText("")
        self.pushButton_min.setObjectName("pushButton_min")
        self.pushButton_max = QtWidgets.QPushButton(self.frame)
        self.pushButton_max.setGeometry(QtCore.QRect(340, 30, 18, 18))
        self.pushButton_max.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_max.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_max.setText("")
        self.pushButton_max.setObjectName("pushButton_max")
        self.verticalLayout_2.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_min.clicked.connect(MainWindow.showMinimized)
        self.pushButton_exit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "\n"
"گذشت از اون روزا چند سالی زود\n"
"\n"
"روزایی که فکرمون شَر بازی بود\n"
"\n"
"به قول تو همون روزایی که الافی بود\n"
"\n"
"اما قشنگ بود هر چند که سر کاری بود\n"
"\n"
"سکوت عجیبی بود شهر خالی بود\n"
"\n"
"یادش بخیر چقدر جنجالی بود\n"
"\n"
"علی شلوغ ولی پر تنهایی بود\n"
"\n"
"اینا خاطرات خوب پارک شهرداری بود\n"
"\n"
"یه سری أ بچه ها جدولی شدن\n"
"\n"
"یه سری بای دادن و رفتنی شدن\n"
"\n"
"واسه نوشتن دردا ورقه کمه\n"
"\n"
"مجبورم بدنمو خط خطی کنم\n"
"\n"
"من یه آدم لالم که زیاده حرفام\n"
"\n"
"یه معتاد لعنتی به سیگار مَگنا\n"
"\n"
"چند سالِ گُمم توو روزایی که گذشت\n"
"\n"
"خودم آجر میزارم رو دیوار غم هام\n"
"\n"
"زیادن توو دل من حرفای نزدم\n"
"\n"
"حرفایی که باعث گرمای تنمن\n"
"\n"
"دردای توو دل تو دردای منم هست\n"
"\n"
"حس می کنمشون با اعضای بدنم\n"
"\n"
"من غروب و خوب دوست دارم\n"
"\n"
"تنمو با سختیا زود جوش دادم\n"
"\n"
"وقتی بهتر میشم اوضاع بدتر نشه\n"
"\n"
"حرفای درویشه خوب گوش دادم\n"
"\n"
"یالا پاشو دیگه بیا سریع بریم دیره\n"
"\n"
"تو همراهم نیای علی نمیشینه\n"
"\n"
"حتی اگه با من هم سلیقه نیستی\n"
"\n"
"یالا پاشو بیا بریم غریبه نیستی\n"
"\n"
"یالا پاتو بزار تووی سفره ی ما\n"
"\n"
"یالا توئم بیا قاطی عُقده ای ها\n"
"\n"
"یه کم نفس بکش توو این هوای سنگین\n"
"\n"
"حالا با کلمه درد جمله بساز\n"
"\n"
"میکشم دردام و مثِ نقاش\n"
"\n"
"میکشم فریاد و مثِ ارواح\n"
"\n"
"میکشم نفس و توو زندگیم باز\n"
"\n"
"میکشم سیگارم و عین فیلما\n"
"\n"
"حالا که هر از گاهی سر میزنی به من\n"
"\n"
"بدون روزایی بود خیلی جنگید علی\n"
"\n"
"چقدر حرف از غصه و غم می زنیم\n"
"\n"
"بی خیال مداد من فروشیه چند میخری\n"
"\n"
"یواش همه چیزای من اینجا حراج\n"
"\n"
"مداد و خودکار و دفتر و تراش\n"
"\n"
"حراج نفس من واسه گُنده تراش\n"
"\n"
"حراج زندگی و تموم اون غماش\n"
"\n"
"قلب من با کلی درد و پارگی و خراش\n"
"\n"
"حتی رفاقت و حتی قشنگی شباش\n"
"\n"
"همه چیزم حراج همه چیزم حراج\n"
"\n"
"اما یادت باشه کردم زندگیمو فداش\n"
"\n"
"تویی که از معرفت دم می زنی\n"
"\n"
"تویی که با همه موزیکای من لب می زنی\n"
"\n"
"تویی که عاشق صدام و حرف منی\n"
"\n"
"اینا همه فروشین بگو چند میخری\n"
"\n"
"میخوام بدونم اصاً اهل جنگیدنی\n"
"\n"
"میخوام بدونم توو غصه ها دم میزنی\n"
"\n"
"به تو نمی یاد تو دنبال خندیدنی\n"
"\n"
"تو دنبال سوژه واسه رقصیدنی\n"
"\n"
"اون مداد الکی نی ، علی مینویسه باهاش\n"
"\n"
"هرجایی میره اونم دیده میشه باهاش\n"
"\n"
"گَلوی ما چند ساله زیر تیغه داداش\n"
"\n"
"پس بده مدادِ بد بیخ ریش صاحابش\n"
"\n"
"الکی نی مینویسه باهاش\n"
"\n"
"هرجایی میره اونم دیده میشه باهاش\n"
"\n"
"گَلوی ما چندساله زیر تیغه داداش\n"
"\n"
"پس بده مدادِ بد بیخ ریش صاحابش\n"
"\n"
"یالا بیا بِره روی دار غرورت\n"
"\n"
"اینجا همه چِته غمن بگو شاد کدومه\n"
"\n"
"یالا الان میره روی دار غرورت\n"
"\n"
"یالا بیا بلرزه چهار ستونت\n"
"\n"
"بیا ببین چطور با زندگیم چِفت شده موزیک\n"
"\n"
"اینجا ماله کسیِ که سِفت کنه پوتین\n"
"\n"
"بهتر برین توو یه کوچه ی خلوت\n"
"\n"
"تو صدای منو یه هدفون کوچیک\n"
"\n"
"شده ببینی یه جوونی که لات راه بره\n"
"\n"
"که با غرور خاص خودش توو پاسگاه بره\n"
"\n"
"نه دنبال دختر و مادمازله\n"
"\n"
"فقط عاشق سه سِریِ گاد فادره\n"
"\n"
"به قرآن قسم دوست دارم تخفیفی به جرمام ندن\n"
"\n"
"شبای منو میدونن قرصام فقط\n"
"\n"
"دوست دارم به هیچ خری قربان نگم\n"
"\n"
"ایراد این زرد نبود ت*مام فقط\n"
"\n"
"ایراد این من بودم با وُجدان طرف\n"
"\n"
"علی سمت جاده های پل دار نرفت\n"
"\n"
"علی سمت دنیای نرمال نرفت\n"
"\n"
"به درک توئم اصاً حرفمو نبین\n"
"\n"
"به درک حرفای قلبمو نبین\n"
"\n"
"به درک پاشو برو دستمو نگیر\n"
"\n"
"ولی به خودت قسم کسی اشکمو ندید\n"
"\n"
"الان بلدم حسابی داد زدنو\n"
"\n"
"حفظم همه روزای باختنمو\n"
"\n"
"همون روزا بودن منو ساختنمو\n"
"\n"
"الان می تونم بزنم حتی شاهرگمو\n"
"\n"
"بلدم داد زدنو ، حفظم همه روزای باختنمو\n"
"\n"
"همون روزا بودن منو ساختنمو\n"
"\n"
"الان می تونم بزنم حتی شاهرگمو\n"
"\n"
"یالا هردردی بود دیدی\n"
"\n"
"یالا پاشو برو دیگه هر چی بود دیدی\n"
"\n"
"حتی اگه فرضی بود دیدی\n"
"\n"
"اگه غمی خشمی یا ترسی بود دیدی\n"
"\n"
"هردردی بود دیدی\n"
"\n"
"یالا پاشو برو دیگه هر چی بود دیدی\n"
"\n"
"حتی اگه فرضی بود دیدی\n"
"\n"
"اگه غمی خشمی یا ترسی بود دیدی"))

