# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'text.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Haf(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(534, 702)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 212, 82);\n"
"\n"
"border-radius:15px;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMouseTracking(False)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 499, 5018))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(0, 5000))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(-130, 80, 600, 4991))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:none;\n"
"color: #f05053;")
        self.label.setObjectName("label")
        self.pushButton_exit = QtWidgets.QPushButton(self.frame)
        self.pushButton_exit.setGeometry(QtCore.QRect(400, 30, 18, 18))
        self.pushButton_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_exit.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_exit.setText("")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_min = QtWidgets.QPushButton(self.frame)
        self.pushButton_min.setGeometry(QtCore.QRect(370, 30, 18, 18))
        self.pushButton_min.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_min.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_min.setText("")
        self.pushButton_min.setObjectName("pushButton_min")
        self.pushButton_back = QtWidgets.QPushButton(self.frame)
        self.pushButton_back.setGeometry(QtCore.QRect(340, 30, 18, 18))
        self.pushButton_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_back.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_back.setText("")
        self.pushButton_back.setObjectName("pushButton_back")
        self.verticalLayout_2.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_min.clicked.connect(MainWindow.showMinimized)
        self.pushButton_exit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "بذار بخونم از همه حوادث تلخ\n"
"\n"
"بذار بخونم از همه شرایط سخت\n"
"\n"
"بذار بخونم بذار همه بدونن\n"
"\n"
"دلیل هیپ هاپ منو دلیل علاقه به رپ\n"
"\n"
"بذار بگم از اونا که فاز هِدو میدنو\n"
"\n"
"از اونا که رو بیتای رپ وِلو میشنو\n"
"\n"
"از اون شخصیتا که ترورینو\n"
"\n"
"بذار بفهمونم معنیِ دل و جیگرو\n"
"\n"
"بذار بگم از مسیرایی که ساده نیست\n"
"\n"
"بذار ببرمت یه جایی که وا بدی\n"
"\n"
"ببینم میتونی خودتو توو ما جا بدی\n"
"\n"
"می خوام رو قلبم بنویسم جای تیر\n"
"\n"
"میخوام کلمه هام بُکنه تو رو له\n"
"\n"
"میخوام نصف کاره نباشه این پروژه\n"
"\n"
"می خوام دست خالی وایسمو داد بزنم\n"
"\n"
"کدوم ننه ق*به می خواد منو بکشه\n"
"\n"
"میخوام تمومه ثانیه های شبمو رپ کنم\n"
"\n"
"واسه مُشت تو لبمو تَر کنم\n"
"\n"
"توو صورت کثیف تو قلمو پَرت کنم\n"
"\n"
"بگو یکی یکی بیان شَرمو کم کنن\n"
"\n"
"نمیتونم باشم اون که متعادله (یا معتاد دل)\n"
"\n"
"ممکنه تا آخر توو دل علی غصه ها بره\n"
"\n"
"تو توو یه خط زنده ای و من هفت خطم\n"
"\n"
"دنیامون متفاوت\n"
"\n"
"هفت خط از چشای تو میخونه\n"
"\n"
"حرفاتو قبل این که نگاه کنی میدونه\n"
"\n"
"هفت خط درد روزگارو میدونه\n"
"\n"
"زندگیه گرگا و زوزه ها رو میدونه\n"
"\n"
"هفت خط توو خیابونا می لوله\n"
"\n"
"عوضیِ مثِ تو رو سر جاش میشونه\n"
"\n"
"هفت خط یه روانی دیوونه\n"
"\n"
"یه فراری بی خونه که شبا میره می خونه\n"
"\n"
"هفت خط از چشای تو میخونه\n"
"\n"
"حرفاتو قبل این که نگاه کنی میدونه\n"
"\n"
"هفت خط درد روزگارو میدونه\n"
"\n"
"زندگیه گرگا و زوزه ها رو میدونه\n"
"\n"
"هفت خط توو خیابونا می لوله\n"
"\n"
"عوضیِ مثِ تو رو سر جاش میشونه\n"
"\n"
"هفت خط یه روانی دیوونه\n"
"\n"
"یه فراری بی خونه که شبا میره می خونه\n"
"\n"
"من میخونم حتی اگه میکروفن بو (بوی) خون بده\n"
"\n"
"شهامت به شعرِ تلخم معنای جُنون میده\n"
"\n"
"باید هرچی بدخواست زیر صدا جون بده\n"
"\n"
"صدای من تموم دنیا رو تکون بده\n"
"\n"
"دنیا رو تکون بده منفجر کنه\n"
"\n"
"حس قدرت من دشمنامو مضطرب کنه\n"
"\n"
"گره منو هیپ هاپو محکمش کنه\n"
"\n"
"فریاد من آدما رو منقلب کنه\n"
"\n"
"باید خورشید همیشه نور به چشام بده\n"
"\n"
"کفشم با کلی غرور خون به پاهام بده\n"
"\n"
"خدا به من و رگم اختیار تام بده\n"
"\n"
"سیگارِ توو دستم همیشه به لبم کام بده\n"
"\n"
"دِ یالا کام بده لا*ی یالا کام بده\n"
"\n"
"منو لای دوده خودت توو آسمون جام بده\n"
"\n"
"منو بپذیر توو درد و دلت راهم بده\n"
"\n"
"بذار ببوسمت بازم حس به صدام بده\n"
"\n"
"هفت خط از چشایِ تو میخونم\n"
"\n"
"حرفاتو قبل این که نگاه کنی میدونم\n"
"\n"
"هفت خط درد روزگارو میدونم\n"
"\n"
"زندگیه گرگا و زوزه ها رو میدونم\n"
"\n"
"دنیا میگه تا اونجا که میتونی بجنگ\n"
"\n"
"تا اونجا که حرفتو می فهمونی بجنگ\n"
"\n"
"من هفت خط شدم تووش اینجوری بگم\n"
"\n"
"سه تا دست چپ ، سه تا پیشونی ، یه لب\n"
"\n"
"هفت خط از چشای تو میخونه\n"
"\n"
"حرفاتو قبل این که نگاه کنی میدونه\n"
"\n"
"هفت خط درد روزگارو میدونه\n"
"\n"
"زندگیه گرگا و زوزه ها رو میدونه\n"
"\n"
"هفت خط توو خیابونا می لوله\n"
"\n"
"عوضیِ مثِ تو رو سر جاش میشونه\n"
"\n"
"هفت خط یه روانی دیوونه\n"
"\n"
"یه فراری بی خونه که شبا میره می خونه\n"
"\n"
"هفت خط از چشای تو میخونه\n"
"\n"
"حرفاتو قبل این که نگاه کنی میدونه\n"
"\n"
"هفت خط درد روزگارو میدونه\n"
"\n"
"زندگیه گرگا و زوزه ها رو میدونه\n"
"\n"
"هفت خط توو خیابونا می لوله\n"
"\n"
"عوضیِ مثِ تو رو سر جاش میشونه\n"
"\n"
"هفت خط یه روانی دیوونه\n"
"\n"
"یه فراری بی خونه که شبا میره می خونه\n"
"\n"
"هفت خط از چشای تو میخونه\n"
"\n"
"حرفاتو قبل این که نگاه کنی میدونه\n"
"\n"
"هفت خط درد روزگارو میدونه\n"
"\n"
"زندگیه گرگا و زوزه ها رو میدونه\n"
"\n"
"هفت خط توو خیابونا می لوله\n"
"\n"
"عوضیِ مثِ تو رو سر جاش میشونه\n"
"\n"
"هفت خط یه روانی دیوونه\n"
"\n"
"یه فراری بی خونه که شبا میره می خونه\n"
"\n"
"هفت خط"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
