# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'marde_tanha.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Kavir(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(475, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd452,stop:0.5 #f05053, stop:1 #ffd452 );\n"
"\n"
"border-radius:15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_kavir = QtWidgets.QPushButton(self.frame)
        self.pushButton_kavir.setEnabled(True)
        self.pushButton_kavir.setGeometry(QtCore.QRect(130, 110, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_kavir.setFont(font)
        self.pushButton_kavir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_kavir.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_kavir.setObjectName("pushButton_kavir")
        self.pushButton_gonjeshkaka = QtWidgets.QPushButton(self.frame)
        self.pushButton_gonjeshkaka.setEnabled(True)
        self.pushButton_gonjeshkaka.setGeometry(QtCore.QRect(130, 170, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_gonjeshkaka.setFont(font)
        self.pushButton_gonjeshkaka.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_gonjeshkaka.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_gonjeshkaka.setObjectName("pushButton_gonjeshkaka")
        self.pushButton_Teryagh = QtWidgets.QPushButton(self.frame)
        self.pushButton_Teryagh.setEnabled(True)
        self.pushButton_Teryagh.setGeometry(QtCore.QRect(130, 230, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Teryagh.setFont(font)
        self.pushButton_Teryagh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Teryagh.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_Teryagh.setObjectName("pushButton_Teryagh")
        self.pushButton_tatre = QtWidgets.QPushButton(self.frame)
        self.pushButton_tatre.setEnabled(True)
        self.pushButton_tatre.setGeometry(QtCore.QRect(130, 290, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_tatre.setFont(font)
        self.pushButton_tatre.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_tatre.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_tatre.setObjectName("pushButton_tatre")
        self.pushButton_poshte = QtWidgets.QPushButton(self.frame)
        self.pushButton_poshte.setEnabled(True)
        self.pushButton_poshte.setGeometry(QtCore.QRect(130, 410, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_poshte.setFont(font)
        self.pushButton_poshte.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_poshte.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_poshte.setObjectName("pushButton_poshte")
        self.pushButton_Maryam = QtWidgets.QPushButton(self.frame)
        self.pushButton_Maryam.setEnabled(True)
        self.pushButton_Maryam.setGeometry(QtCore.QRect(130, 350, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Maryam.setFont(font)
        self.pushButton_Maryam.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Maryam.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_Maryam.setObjectName("pushButton_Maryam")
        self.pushButtoon_nafir = QtWidgets.QPushButton(self.frame)
        self.pushButtoon_nafir.setEnabled(True)
        self.pushButtoon_nafir.setGeometry(QtCore.QRect(130, 470, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtoon_nafir.setFont(font)
        self.pushButtoon_nafir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtoon_nafir.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButtoon_nafir.setObjectName("pushButtoon_nafir")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(179, 10, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Dosis ExtraBold")
        font.setPointSize(31)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: none;\n"
"color:#ffd452;\n"
"")
        self.label.setObjectName("label")
        self.pushButton_exit = QtWidgets.QPushButton(self.frame)
        self.pushButton_exit.setGeometry(QtCore.QRect(400, 44, 18, 18))
        self.pushButton_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_exit.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_exit.setText("")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_back = QtWidgets.QPushButton(self.frame)
        self.pushButton_back.setGeometry(QtCore.QRect(400, 112, 18, 18))
        self.pushButton_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_back.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_back.setText("")
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_min = QtWidgets.QPushButton(self.frame)
        self.pushButton_min.setGeometry(QtCore.QRect(400, 78, 18, 18))
        self.pushButton_min.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_min.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_min.setText("")
        self.pushButton_min.setObjectName("pushButton_min")
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_exit.clicked.connect(MainWindow.close)
        self.pushButton_min.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_kavir.setText(_translate("MainWindow", "Kavir"))
        self.pushButton_gonjeshkaka.setText(_translate("MainWindow", "Gonjeshkaka"))
        self.pushButton_Teryagh.setText(_translate("MainWindow", "Teryagh"))
        self.pushButton_tatre.setText(_translate("MainWindow", "Tatre-sayeha"))
        self.pushButton_poshte.setText(_translate("MainWindow", "Poshte-in-jang-ha"))
        self.pushButton_Maryam.setText(_translate("MainWindow", "Maryam"))
        self.pushButtoon_nafir.setText(_translate("MainWindow", "Nafir"))
        self.label.setText(_translate("MainWindow", "Kavir"))


