# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'marde_tanha.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Marde_Tanha(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(406, 665)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd452,stop:0.5 #f05053, stop:1 #ffd452 );\n"
"\n"
"border-radius:15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_gharibe = QtWidgets.QPushButton(self.frame)
        self.pushButton_gharibe.setEnabled(True)
        self.pushButton_gharibe.setGeometry(QtCore.QRect(107, 110, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_gharibe.setFont(font)
        self.pushButton_gharibe.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_gharibe.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_gharibe.setObjectName("pushButton_gharibe")
        self.pushButton_beshnas = QtWidgets.QPushButton(self.frame)
        self.pushButton_beshnas.setEnabled(True)
        self.pushButton_beshnas.setGeometry(QtCore.QRect(107, 160, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_beshnas.setFont(font)
        self.pushButton_beshnas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_beshnas.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_beshnas.setObjectName("pushButton_beshnas")
        self.pushButton_Taghsir = QtWidgets.QPushButton(self.frame)
        self.pushButton_Taghsir.setEnabled(True)
        self.pushButton_Taghsir.setGeometry(QtCore.QRect(107, 210, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Taghsir.setFont(font)
        self.pushButton_Taghsir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Taghsir.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_Taghsir.setObjectName("pushButton_Taghsir")
        self.pushButton_Masti = QtWidgets.QPushButton(self.frame)
        self.pushButton_Masti.setEnabled(True)
        self.pushButton_Masti.setGeometry(QtCore.QRect(107, 260, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Masti.setFont(font)
        self.pushButton_Masti.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Masti.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_Masti.setObjectName("pushButton_Masti")
        self.pushButton_doel = QtWidgets.QPushButton(self.frame)
        self.pushButton_doel.setEnabled(True)
        self.pushButton_doel.setGeometry(QtCore.QRect(107, 360, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_doel.setFont(font)
        self.pushButton_doel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_doel.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_doel.setObjectName("pushButton_doel")
        self.pushButton_Khake = QtWidgets.QPushButton(self.frame)
        self.pushButton_Khake.setEnabled(True)
        self.pushButton_Khake.setGeometry(QtCore.QRect(107, 460, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Khake.setFont(font)
        self.pushButton_Khake.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Khake.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_Khake.setObjectName("pushButton_Khake")
        self.pushButton_zendegi = QtWidgets.QPushButton(self.frame)
        self.pushButton_zendegi.setEnabled(True)
        self.pushButton_zendegi.setGeometry(QtCore.QRect(107, 310, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_zendegi.setFont(font)
        self.pushButton_zendegi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_zendegi.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_zendegi.setObjectName("pushButton_zendegi")
        self.pushButtoon_Haf = QtWidgets.QPushButton(self.frame)
        self.pushButtoon_Haf.setEnabled(True)
        self.pushButtoon_Haf.setGeometry(QtCore.QRect(107, 410, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtoon_Haf.setFont(font)
        self.pushButtoon_Haf.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtoon_Haf.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButtoon_Haf.setObjectName("pushButtoon_Haf")
        self.pushButton_bad = QtWidgets.QPushButton(self.frame)
        self.pushButton_bad.setEnabled(True)
        self.pushButton_bad.setGeometry(QtCore.QRect(107, 560, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_bad.setFont(font)
        self.pushButton_bad.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_bad.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_bad.setObjectName("pushButton_bad")
        self.pushButton_Vaghte = QtWidgets.QPushButton(self.frame)
        self.pushButton_Vaghte.setEnabled(True)
        self.pushButton_Vaghte.setGeometry(QtCore.QRect(107, 510, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Vaghte.setFont(font)
        self.pushButton_Vaghte.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Vaghte.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_Vaghte.setObjectName("pushButton_Vaghte")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(90, 20, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Dosis ExtraBold")
        font.setPointSize(31)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: none;\n"
"color:#ffd452;\n"
"")
        self.label.setObjectName("label")
        self.pushButton_exit = QtWidgets.QPushButton(self.frame)
        self.pushButton_exit.setGeometry(QtCore.QRect(340, 44, 18, 18))
        self.pushButton_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_exit.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_exit.setText("")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_back = QtWidgets.QPushButton(self.frame)
        self.pushButton_back.setGeometry(QtCore.QRect(340, 112, 18, 18))
        self.pushButton_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_back.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_back.setText("")
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_min = QtWidgets.QPushButton(self.frame)
        self.pushButton_min.setGeometry(QtCore.QRect(340, 78, 18, 18))
        self.pushButton_min.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_min.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_min.setText("")
        self.pushButton_min.setObjectName("pushButton_min")
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_exit.clicked.connect(MainWindow.close)
        self.pushButton_min.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_gharibe.setText(_translate("MainWindow", "Gharibe-nisti"))
        self.pushButton_beshnas.setText(_translate("MainWindow", "Beshnas"))
        self.pushButton_Taghsir.setText(_translate("MainWindow", "Taghsir"))
        self.pushButton_Masti.setText(_translate("MainWindow", "Masti"))
        self.pushButton_doel.setText(_translate("MainWindow", "Doel"))
        self.pushButton_Khake.setText(_translate("MainWindow", "Khake-sorkh"))
        self.pushButton_zendegi.setText(_translate("MainWindow", "Zendegi-hiphopi"))
        self.pushButtoon_Haf.setText(_translate("MainWindow", "Haf-khat"))
        self.pushButton_bad.setText(_translate("MainWindow", "Ba\'d-az-man"))
        self.pushButton_Vaghte.setText(_translate("MainWindow", "Vaghte-khab-nist"))
        self.label.setText(_translate("MainWindow", "Marde-Tanha"))
