# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'text.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Masti(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(524, 667)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 212, 82);\n"
"\n"
"border-radius:15px;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMouseTracking(False)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 489, 5018))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(0, 5000))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, -1230, 451, 4991))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:none;\n"
"color: #f05053;")
        self.label.setObjectName("label")
        self.pushButton_exit = QtWidgets.QPushButton(self.frame)
        self.pushButton_exit.setGeometry(QtCore.QRect(400, 30, 18, 18))
        self.pushButton_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_exit.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_exit.setText("")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_min = QtWidgets.QPushButton(self.frame)
        self.pushButton_min.setGeometry(QtCore.QRect(370, 30, 18, 18))
        self.pushButton_min.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_min.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_min.setText("")
        self.pushButton_min.setObjectName("pushButton_min")
        self.pushButton_back = QtWidgets.QPushButton(self.frame)
        self.pushButton_back.setGeometry(QtCore.QRect(340, 30, 18, 18))
        self.pushButton_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_back.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_back.setText("")
        self.pushButton_back.setObjectName("pushButton_back")
        self.verticalLayout_2.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_min.clicked.connect(MainWindow.showMinimized)
        self.pushButton_exit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "رفیق من امشب بد مستم\n"
"\n"
"یا زیاد خوردم یا کم جنبم\n"
"\n"
"پل تگری زدنو رد کردم\n"
"\n"
"اصاً نمیدونم که با خودم چند چندم\n"
"\n"
"من دچار سر دردم\n"
"\n"
"تب دارم یه جورایی لش کردم\n"
"\n"
"پی شکسته بندو این داستانا نباش\n"
"\n"
"من بدجوری از خودم در رفتم\n"
"\n"
"خیلی خوردم ولی هنوز نمردم\n"
"\n"
"این الکلا هنوز منو نکشتن\n"
"\n"
"فراموش کارم ایرادم اینه\n"
"\n"
"پیک خالی جلومو و میگم هنوز نخوردم\n"
"\n"
"بریز پیک بعد و علی نسخ توئه\n"
"\n"
"دم ساقی گرم و سبد پرش\n"
"\n"
"این که زیاد خوردم این نظر توئه\n"
"\n"
"هر پیک پیک یه خبر نوئه\n"
"\n"
"شاید ریختن اینا تو رو خسته کنه\n"
"\n"
"بِده من بریزم از اول دست توئه\n"
"\n"
"بخور نوش دم هرچی مستی خوره\n"
"\n"
"بزار یه قصه بگم واست مزه کنه\n"
"\n"
"یه یارو بود می گفتن پهلوونه\n"
"\n"
"هر روز می رفت توویِ قهوه خونه\n"
"\n"
"دو تا بطری عرق و دوتا استکان میخواست\n"
"\n"
"می شست می خورد میرفت مست تا خونه\n"
"\n"
"تا اون قهوه چی پرسید صبح تا میای\n"
"\n"
"تا آخر شبش که شل راه میای\n"
"\n"
"عرق یا ویسکی و ودکا میخوای\n"
"\n"
"چرا از هر کدومشون دوتا میخوای\n"
"\n"
"گفت ما سه تا بودیم سه تا رفیق\n"
"\n"
"قول دادیم هر جایی تنها بریم\n"
"\n"
"جای هم بخوریم جای هم مست کنیم\n"
"\n"
"جای خالی همدیگه بره پیک روی میز\n"
"\n"
"گفت باشه ولی هرچی گشتم\n"
"\n"
"گفتی سه تا اینا ، دوتاست و من توو شکم\n"
"\n"
"یارو یه نگاه بهش کرد و بعد با لبخند\n"
"\n"
"گفت این سهم اون دوتاست من توو ترکم\n"
"\n"
"مستی راستی کولیا بردن\n"
"\n"
"منم کولیم واسه همین جفت آوردم\n"
"\n"
"یارو خیلی مرد بود قده دونفر خورد\n"
"\n"
"من چی بگم که قده دنیا خوردم\n"
"\n"
"مستی راستی کولیا بردن\n"
"\n"
"منم کولیم واسه همین جفت آوردم\n"
"\n"
"یارو خیلی مرد بود قده دونفر خورد\n"
"\n"
"من چی بگم که قده دنیا خوردم\n"
"\n"
"مستی راستی کولیا بردن\n"
"\n"
"منم کولیم واسه همین جفت آوردم\n"
"\n"
"یارو خیلی مرد بود قده دونفر خورد\n"
"\n"
"من چی بگم که قده دنیا خوردم"))


