# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'marde_tanha.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Negar(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(621, 602)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd452,stop:0.5 #f05053, stop:1 #ffd452 );\n"
"\n"
"border-radius:15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_tavalod = QtWidgets.QPushButton(self.frame)
        self.pushButton_tavalod.setEnabled(True)
        self.pushButton_tavalod.setGeometry(QtCore.QRect(110, 100, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_tavalod.setFont(font)
        self.pushButton_tavalod.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_tavalod.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_tavalod.setObjectName("pushButton_tavalod")
        self.pushButton_berim = QtWidgets.QPushButton(self.frame)
        self.pushButton_berim.setEnabled(True)
        self.pushButton_berim.setGeometry(QtCore.QRect(110, 160, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_berim.setFont(font)
        self.pushButton_berim.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_berim.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_berim.setObjectName("pushButton_berim")
        self.pushButton_nagar = QtWidgets.QPushButton(self.frame)
        self.pushButton_nagar.setEnabled(True)
        self.pushButton_nagar.setGeometry(QtCore.QRect(110, 220, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_nagar.setFont(font)
        self.pushButton_nagar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_nagar.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_nagar.setObjectName("pushButton_nagar")
        self.pushButton_naghsh = QtWidgets.QPushButton(self.frame)
        self.pushButton_naghsh.setEnabled(True)
        self.pushButton_naghsh.setGeometry(QtCore.QRect(110, 280, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_naghsh.setFont(font)
        self.pushButton_naghsh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_naghsh.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_naghsh.setObjectName("pushButton_naghsh")
        self.pushButton_jari = QtWidgets.QPushButton(self.frame)
        self.pushButton_jari.setEnabled(True)
        self.pushButton_jari.setGeometry(QtCore.QRect(110, 400, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_jari.setFont(font)
        self.pushButton_jari.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_jari.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_jari.setObjectName("pushButton_jari")
        self.pushButton_keshti = QtWidgets.QPushButton(self.frame)
        self.pushButton_keshti.setEnabled(True)
        self.pushButton_keshti.setGeometry(QtCore.QRect(110, 340, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_keshti.setFont(font)
        self.pushButton_keshti.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_keshti.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_keshti.setObjectName("pushButton_keshti")
        self.pushButtoon_morphin = QtWidgets.QPushButton(self.frame)
        self.pushButtoon_morphin.setEnabled(True)
        self.pushButtoon_morphin.setGeometry(QtCore.QRect(110, 460, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtoon_morphin.setFont(font)
        self.pushButtoon_morphin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtoon_morphin.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButtoon_morphin.setObjectName("pushButtoon_morphin")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(252, 10, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Dosis ExtraBold")
        font.setPointSize(31)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: none;\n"
"color:#ffd452;\n"
"")
        self.label.setObjectName("label")
        self.pushButton_exit = QtWidgets.QPushButton(self.frame)
        self.pushButton_exit.setGeometry(QtCore.QRect(550, 44, 18, 18))
        self.pushButton_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_exit.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_exit.setText("")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_back = QtWidgets.QPushButton(self.frame)
        self.pushButton_back.setGeometry(QtCore.QRect(550, 112, 18, 18))
        self.pushButton_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_back.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_back.setText("")
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_min = QtWidgets.QPushButton(self.frame)
        self.pushButton_min.setGeometry(QtCore.QRect(550, 78, 18, 18))
        self.pushButton_min.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_min.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_min.setText("")
        self.pushButton_min.setObjectName("pushButton_min")
        self.pushButton_atash = QtWidgets.QPushButton(self.frame)
        self.pushButton_atash.setEnabled(True)
        self.pushButton_atash.setGeometry(QtCore.QRect(310, 159, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_atash.setFont(font)
        self.pushButton_atash.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_atash.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_atash.setObjectName("pushButton_atash")
        self.pushButton_tark = QtWidgets.QPushButton(self.frame)
        self.pushButton_tark.setEnabled(True)
        self.pushButton_tark.setGeometry(QtCore.QRect(310, 100, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_tark.setFont(font)
        self.pushButton_tark.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_tark.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_tark.setObjectName("pushButton_tark")
        self.pushButton_paak = QtWidgets.QPushButton(self.frame)
        self.pushButton_paak.setEnabled(True)
        self.pushButton_paak.setGeometry(QtCore.QRect(310, 220, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_paak.setFont(font)
        self.pushButton_paak.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_paak.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_paak.setObjectName("pushButton_paak")
        self.pushButton_toorbin = QtWidgets.QPushButton(self.frame)
        self.pushButton_toorbin.setEnabled(True)
        self.pushButton_toorbin.setGeometry(QtCore.QRect(310, 280, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_toorbin.setFont(font)
        self.pushButton_toorbin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_toorbin.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_toorbin.setObjectName("pushButton_toorbin")
        self.pushButton_toofan = QtWidgets.QPushButton(self.frame)
        self.pushButton_toofan.setEnabled(True)
        self.pushButton_toofan.setGeometry(QtCore.QRect(310, 340, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_toofan.setFont(font)
        self.pushButton_toofan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_toofan.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_toofan.setObjectName("pushButton_toofan")
        self.pushButton_marg = QtWidgets.QPushButton(self.frame)
        self.pushButton_marg.setEnabled(True)
        self.pushButton_marg.setGeometry(QtCore.QRect(310, 400, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_marg.setFont(font)
        self.pushButton_marg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_marg.setStyleSheet("QPushButton{\n"
"  background-color :#ffd452;\n"
"  color:#f05053;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color :#f05053;\n"
"  color:#ffd452;\n"
"}")
        self.pushButton_marg.setObjectName("pushButton_marg")
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_exit.clicked.connect(MainWindow.close)
        self.pushButton_min.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_tavalod.setText(_translate("MainWindow", "Tavalod"))
        self.pushButton_berim.setText(_translate("MainWindow", "Berim-aghabtar"))
        self.pushButton_nagar.setText(_translate("MainWindow", "nagar"))
        self.pushButton_naghsh.setText(_translate("MainWindow", "naghsh"))
        self.pushButton_jari.setText(_translate("MainWindow", "Jaari"))
        self.pushButton_keshti.setText(_translate("MainWindow", "Keshti"))
        self.pushButtoon_morphin.setText(_translate("MainWindow", "Morphin"))
        self.label.setText(_translate("MainWindow", "Negar"))
        self.pushButton_atash.setText(_translate("MainWindow", "Atash"))
        self.pushButton_tark.setText(_translate("MainWindow", "Tark"))
        self.pushButton_paak.setText(_translate("MainWindow", "Paak"))
        self.pushButton_toorbin.setText(_translate("MainWindow", "Toorbin"))
        self.pushButton_toofan.setText(_translate("MainWindow", "Toofan"))
        self.pushButton_marg.setText(_translate("MainWindow", "Marg"))

