# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sign_up(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(483, 656)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 461, 633))
        self.frame_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd452,stop:0.5 #f05053 , stop:1 #ffd452 );\n"
"\n"
"border-radius:15px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit_password_signup = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_password_signup.setGeometry(QtCore.QRect(100, 410, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_password_signup.setFont(font)
        self.lineEdit_password_signup.setStyleSheet("background-color:rgb(255, 212, 82);\n"
"color:rgb(240, 80, 83);\n"
"border-radius :10px;\n"
"")
        self.lineEdit_password_signup.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password_signup.setObjectName("lineEdit_password_signup")
        self.lineEdit_username_signup = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_username_signup.setGeometry(QtCore.QRect(100, 364, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_username_signup.setFont(font)
        self.lineEdit_username_signup.setStyleSheet("background-color:rgb(255, 212, 82);\n"
"color:rgb(240, 80, 83);\n"
"border-radius :10px;\n"
"")
        self.lineEdit_username_signup.setText("")
        self.lineEdit_username_signup.setObjectName("lineEdit_username_signup")
        self.label_1 = QtWidgets.QLabel(self.frame_2)
        self.label_1.setGeometry(QtCore.QRect(70, 150, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Dosis ExtraBold")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("color: #ffd452 ;\n"
"background-color: none;\n"
"")
        self.label_1.setObjectName("label_1")
        self.label_axuck = QtWidgets.QLabel(self.frame_2)
        self.label_axuck.setGeometry(QtCore.QRect(146, 60, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(33)
        self.label_axuck.setFont(font)
        self.label_axuck.setStyleSheet("color:#ffd452 ;\n"
"background-color: none;\n"
"")
        self.label_axuck.setObjectName("label_axuck")
        self.pushButton_login = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_login.setGeometry(QtCore.QRect(160, 530, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(15)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_login.setStyleSheet("QPushButton{\n"
"color:#f05053;\n"
"background-color:rgb(255, 212, 82);\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(255, 212, 82);\n"
"background-color:#f05053;\n"
"}\n"
"")
        self.pushButton_login.setObjectName("pushButton_login")
        self.pushButton_min_signup = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_min_signup.setGeometry(QtCore.QRect(387, 90, 18, 18))
        self.pushButton_min_signup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_min_signup.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:8px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:8px;\n"
"}\n"
"")
        self.pushButton_min_signup.setText("")
        self.pushButton_min_signup.setObjectName("pushButton_min_signup")
        self.pushButton_exit_signup = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_exit_signup.setGeometry(QtCore.QRect(387, 56, 18, 18))
        self.pushButton_exit_signup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_exit_signup.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:8px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:8px;\n"
"}\n"
"")
        self.pushButton_exit_signup.setText("")
        self.pushButton_exit_signup.setObjectName("pushButton_exit_signup")
        self.pushButton_back_signup = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_back_signup.setGeometry(QtCore.QRect(387, 124, 18, 18))
        self.pushButton_back_signup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_back_signup.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:8px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:8px;\n"
"}\n"
"")
        self.pushButton_back_signup.setText("")
        self.pushButton_back_signup.setObjectName("pushButton_back_signup")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(53, 208, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Dosis ExtraBold")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #ffd452 ;\n"
"background-color: none;\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(86, 266, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Dosis ExtraBold")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #ffd452 ;\n"
"background-color: none;\n"
"")
        self.label_3.setObjectName("label_3")
        self.lineEdit_password_signup_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_password_signup_2.setGeometry(QtCore.QRect(100, 457, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_password_signup_2.setFont(font)
        self.lineEdit_password_signup_2.setStyleSheet("background-color:rgb(255, 212, 82);\n"
"color:rgb(240, 80, 83);\n"
"border-radius :10px;\n"
"")
        self.lineEdit_password_signup_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password_signup_2.setObjectName("lineEdit_password_signup_2")
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_exit_signup.clicked.connect(MainWindow.close)
        self.pushButton_min_signup.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_1.setText(_translate("MainWindow", "However, it\'s not as easy "))
        self.label_axuck.setText(_translate("MainWindow", "AXUCK"))
        self.pushButton_login.setText(_translate("MainWindow", "Sign up"))
        self.label_2.setText(_translate("MainWindow", " to cancel your account as"))
        self.label_3.setText(_translate("MainWindow", "it was to sign up for it."))


