# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'succsespage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(466, 251)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 20, 431, 211))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #f05053,\n"
"stop:0.5 #ffd452, stop:1 #f05053);\n"
"border-radius:15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(67, 70, 260, 71))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(48)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color :none;\n"
"color:#f05053;")
        self.label.setObjectName("label")
        self.pushButton_exit = QtWidgets.QPushButton(self.frame)
        self.pushButton_exit.setGeometry(QtCore.QRect(390, 50, 18, 18))
        self.pushButton_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_exit.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:8px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #f05053;\n"
"border-radius:8px;\n"
"}\n"
"")
        self.pushButton_exit.setText("")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_max = QtWidgets.QPushButton(self.frame)
        self.pushButton_max.setGeometry(QtCore.QRect(390, 100, 18, 18))
        self.pushButton_max.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_max.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:8px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #f05053;\n"
"border-radius:8px;\n"
"}\n"
"")
        self.pushButton_max.setText("")
        self.pushButton_max.setObjectName("pushButton_max")
        self.pushButton_min = QtWidgets.QPushButton(self.frame)
        self.pushButton_min.setGeometry(QtCore.QRect(390, 150, 18, 18))
        self.pushButton_min.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_min.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:8px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #f05053;\n"
"border-radius:8px;\n"
"}\n"
"")
        self.pushButton_min.setText("")
        self.pushButton_min.setObjectName("pushButton_min")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_exit.clicked.connect(MainWindow.showMinimized)
        self.pushButton_max.clicked.connect(MainWindow.showMaximized)
        self.pushButton_min.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "AXUCK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
