# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'text.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Taghsir(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(524, 667)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 212, 82);\n"
"\n"
"border-radius:15px;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMouseTracking(False)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 489, 5018))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(0, 5000))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(-10, -370, 451, 4991))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:none;\n"
"color: #f05053;")
        self.label.setObjectName("label")
        self.pushButton_exit = QtWidgets.QPushButton(self.frame)
        self.pushButton_exit.setGeometry(QtCore.QRect(400, 30, 18, 18))
        self.pushButton_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_exit.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_exit.setText("")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_min = QtWidgets.QPushButton(self.frame)
        self.pushButton_min.setGeometry(QtCore.QRect(370, 30, 18, 18))
        self.pushButton_min.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_min.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_min.setText("")
        self.pushButton_min.setObjectName("pushButton_min")
        self.pushButton_back = QtWidgets.QPushButton(self.frame)
        self.pushButton_back.setGeometry(QtCore.QRect(340, 30, 18, 18))
        self.pushButton_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_back.setStyleSheet("QPushButton{\n"
"background-color:#f05053;\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 82);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pushButton_back.setText("")
        self.pushButton_back.setObjectName("pushButton_back")
        self.verticalLayout_2.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_min.clicked.connect(MainWindow.showMinimized)
        self.pushButton_exit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ما چند سالی میگذره که بینمون جنگه\n"
"\n"
"اما جفتمون دلمون تنگه\n"
"\n"
"وقتی یاد اون روزام میشکنم فقط همین\n"
"\n"
"چپ و راست از اینور اونور میشنوم ازت رفیق\n"
"\n"
"شنیدم هنوز نسبت به اجتماع سردی\n"
"\n"
"هنوزم توو لحظه دنبال یکی میگردی\n"
"\n"
"هنوزم مثِ قدیما نوشته هات بد نی\n"
"\n"
"تلخیاتو می ریزی توو یه استکان تلخی\n"
"\n"
"هنوز تنو میسپاری به سرمای بارون\n"
"\n"
"جُک تعریف می کنی با حرفای ناجور\n"
"\n"
"هنوز این و اون دست میندازی مثِ قدیم\n"
"\n"
"با هزار تا حرکت أ برگای پاسور\n"
"\n"
"تووی راهی رفتی انگار بقیشو مجبوری\n"
"\n"
"هنوز فکر می کنی که به خیلیا مدیونی\n"
"\n"
"دنیا شکستت ، صداشو فقط شنید قلبت\n"
"\n"
"آره بدجوری شکستت ولی هنوز مغروری\n"
"\n"
"هنوز صدات گم میشه میون مردم میره\n"
"\n"
"دلت سریع پر میشه دم نمیزنی اما\n"
"\n"
"قشنگ میشه فهمید چون هنوز مثه قدیما\n"
"\n"
"چشات تو رو لو می ده\n"
"\n"
"یه شکل و یه طور دیگه\n"
"\n"
"هنوز لالایی میگی غمات و خواب میکنی\n"
"\n"
"یه جوری توو خیابونا تاب میخوری\n"
"\n"
"هنوز لاشخور أ خیابونا پاک میکنی\n"
"\n"
"هنوز دهن هر آشغال و صاف میکنی\n"
"\n"
"هنوز همه دارن می خندن به قصه هات\n"
"\n"
"چوب میکنن لاچرخ نوشته هات\n"
"\n"
"من چند سالی بود کنارت نبودم مشتی\n"
"\n"
"ولی خلاصه خوشحالم هنوزم هستی\n"
"\n"
"هنوزم مثِ قدیما بدون خط کشی موندی\n"
"\n"
"هنوز مثِ خاطرات خوب بچگیمونی\n"
"\n"
"هنوز کلی ترس داری از پیر شدن\n"
"\n"
"همه بزرگ میشن ولی تو بچه میمونی\n"
"\n"
"هنوز مثِ قدیما بدون خط کشی موندی\n"
"\n"
"هنوز مثِ خاطرات خوبه بچگیمونی\n"
"\n"
"هنوز کلی ترس توو دلت هست از پیر شدن\n"
"\n"
"همه بزرگ میشن ولی تو بچه میمونی\n"
"\n"
"هنوز مثِ قدیما بدون خط کشی موندی\n"
"\n"
"هنوز مثِ خاطرات خوبه بچگیمونی\n"
"\n"
"هنوز کلی ترس توو دلت هست از پیر شدن\n"
"\n"
"همه بزرگ میشن ولی تو بچه میمونی\n"
"\n"
"قبول من اصاً نبودم مواظب تو\n"
"\n"
"ولی تو مثِ مرد باش و پاشو مبارزه کن\n"
"\n"
"میگی دلیل تمومه مشکلاتِ تو منم\n"
"\n"
"باشه هر جور میخوای محاکمه کن\n"
"\n"
"اصاً من باعث همه مسیرای کَجتم\n"
"\n"
"اصاً من باعث همه رَفیقای بدتم\n"
"\n"
"من دلیل غمتم ، من الکل شبتم\n"
"\n"
"من باعث سه تا خط کج رو دستِ چپتم\n"
"\n"
"من بودم که مُردم ، من زندگیتو بُردم\n"
"\n"
"این من بودم که حتی عشقِ تو رو کشتم\n"
"\n"
"من بودم که گ*ه زدم توو روزای با حال تو\n"
"\n"
"من گرفتم حتی ازت دوستای پا کارتو\n"
"\n"
"من بودم که ظلم می کردم به تنو باور تو\n"
"\n"
"منم حتی دلیل غم پدر و مادر تو\n"
"\n"
"منم حتی دلیل کبودی رویِ تن تو\n"
"\n"
"منم حتی دلیل ریزش موهای سرتو\n"
"\n"
"منم حتی دلیل شروع به هیپ هاپ و رپتو\n"
"\n"
"من یادمه قشنگ اولین روز هِد زدنتو\n"
"\n"
"من بودم می گفتم لای کلمه ها تَب کنی\n"
"\n"
"هر اعتراضی که داری بنویسی و رپ کنی\n"
"\n"
"من بودم می گفتم که تو نباید صبر کنی\n"
"\n"
"باید همیشه تند بری حتی اگه چپ کنی\n"
"\n"
"من بودم می گفتم که تو نباید صبر کنی\n"
"\n"
"باید همیشه تند بری حتی اگه چپ کنی\n"
"\n"
"نگاه تو از توو آیینه رو تصویر من ننداز\n"
"\n"
"هر اتفاقی افتاده تقصیر من ننداز\n"
"\n"
"تو بیست و یک ساله فقط یه تصویری توو آیینه\n"
"\n"
"هر اتفاقی افتاده تقصیر من ننداز\n"
"\n"
"هنوز مثِ قدیما بدون خط کشی موندی\n"
"\n"
"هنوز مثِ خاطرات خوبه بچگیمونی\n"
"\n"
"هنوز کلی ترس توو دلت هست از پیر شدن\n"
"\n"
"همه بزرگ میشن ولی تو بچه می مونی\n"
"\n"
"هنوز مثِ قدیما بدون خط کشی موندی\n"
"\n"
"هنوز مثِ خاطرات خوبه بچگیمونی\n"
"\n"
"هنوز کلی ترس توو دلت هست از پیر شدن\n"
"\n"
"همه بزرگ میشن ولی تو بچه میمونی\n"
"\n"
"هنوز مثِ قدیما بدون خط کشی موندی\n"
"\n"
"هنوز مثِ خاطرات خوبه بچگیمونی\n"
"\n"
"هنوز کلی ترس توو دلت هست از پیر شدن\n"
"\n"
"همه بزرگ میشن ولی تو بچه میمونی"))


